apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-ex1-09
  namespace: log-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ping-pong-app
  template:
    metadata:
      labels:
        app: ping-pong-app
    spec:
      volumes:
        - name: shared-bucket
          persistentVolumeClaim:
            claimName: log-app-pv-claim
      containers:
        - name: ping-pong-app
          image: jamesho287/kube-ex1-09:v0.2
          imagePullPolicy: IfNotPresent
          volumeMounts:
          - name: shared-bucket
            mountPath: /usr/src/app/files