apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: kube-ex1-09-hpa
  namespace: log-app
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: kube-ex1-09
  minReplicas: 1
  maxReplicas: 2
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 30