apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: pingpong-knative
spec:
  template:
    metadata:
      name: pingpong-knative-v1
    spec:
      containers:
        - image: jamesho287/kube-ex1-09:v0.1
          ports:
            - containerPort: 8081
  traffic: # split traffic between revisions
  - revisionName: pingpong-knative-v1
    percent: 100