apiVersion: v1
kind: Service
metadata:
  name: kube-ex1-09
  namespace: log-app
spec:
  type: NodePort
  selector:
    app: ping-pong-app
  ports:
    - port: 80
      protocol: TCP
      targetPort: 3500