apiVersion: v1
kind: Service
metadata:
  name: ping-pong-svc
  namespace: log-app
spec:
  type: ClusterIP
  selector:
    app: ping-pong-app
  ports:
    - port: 8005
      protocol: TCP
      targetPort: 3500